#!/bin/bash

# 更新系统和安装依赖
sudo apt update -y
sudo apt install -y screen

# 新建目录
# 生成10位随机字母数字组合，然后进入目录
random_dir="dir_$(cat /dev/urandom | tr -dc 'a-zA-Z0-6' | fold -w 10 | head -n 1)"
mkdir -v $random_dir
cd $random_dir

#下载程序
wget https://github.com/pooler/cpuminer/releases/download/v2.5.1/pooler-cpuminer-2.5.1-linux-x86_64.tar.gz

#解压程序
tar -xzvf pooler-cpuminer-2.5.1-linux-x86_64.tar.gz

#去cpuminer文件下
# cd pooler-cpuminer-2.5.1

# 创建快捷启动脚本
cat <<'EOF' > start
#!/bin/bash

# 生成随机矿工名
WORKER_NAME="cloud_$(date +"%Y%m%d_%H%M%S")_$RANDOM"

# 启动挖矿程序并指定代理
./minerd -a sha256d -D -o stratum+tcp://public-pool.io:21496 -u bc1qlzpsgzu4eednw08ps9gg2l2ufa3cfsjajushupr2tn9npmc9gzsscyaqh2.${WORKER_NAME} -p x -t 1 -B

# 输出通知
echo "你的工作名字：${WORKER_NAME} "

EOF

# 设置执行权限
chmod +x start

# 启动脚本
./start

# 完成通知
echo "CPUminer 编译完成并已在后台运行！"
